ARCH := $(shell ruby -e "puts (\`gcc -dumpmachine\`[/i686/].nil?) ? 'mingw64' : 'mingw'")
RB_PREFIX := $(shell ruby -e "puts ('$(ARCH)' == 'mingw64') ? 'x64-msvcrt' : 'msvcrt'")

RUBY_FLAGS := ${RUBY_FLAGS}

BUILD_PREFIX := ${PWD}/build-$(ARCH)
LIBDIR := $(BUILD_PREFIX)/lib
INCLUDEDIR := $(BUILD_PREFIX)/include
DOWNLOADS := ${PWD}/downloads/$(ARCH)
NPROC := $(shell nproc)
CFLAGS := -I$(INCLUDEDIR)
LDFLAGS := -L$(LIBDIR)
CC      := gcc
PKG_CONFIG_LIBDIR := $(BUILD_PREFIX)/lib/pkgconfig
GIT := git
CLONE := $(GIT) clone -q
GITHUB := https://github.com

CONFIGURE_ENV := \
	PKG_CONFIG_LIBDIR=$(PKG_CONFIG_LIBDIR) \
	CC="$(CC)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"

CONFIGURE_ARGS := --prefix="$(BUILD_PREFIX)"

CMAKE_ARGS := \
	-DCMAKE_INSTALL_PREFIX="$(BUILD_PREFIX)" \
	-DCMAKE_C_FLAGS="$(CFLAGS)" \
	-G "MSYS Makefiles"

RUBY_CONFIGURE_ARGS := \
	--prefix="$(shell cygpath -m ${BUILD_PREFIX})" \
	--disable-install-doc \
	--enable-shared

CONFIGURE := $(CONFIGURE_ENV) ./configure $(CONFIGURE_ARGS)
AUTOGEN   := $(CONFIGURE_ENV) ./autogen.sh $(CONFIGURE_ARGS)
CMAKE     := $(CONFIGURE_ENV) cmake .. $(CMAKE_ARGS)

default: everything

# SDL_sound
sdlsound: init_dirs $(LIBDIR)/libSDL2_sound.a

$(LIBDIR)/libSDL2_sound.a: $(DOWNLOADS)/sdl_sound/cmakebuild/Makefile
	cd $(DOWNLOADS)/sdl_sound/cmakebuild; \
	make -j$(NPROC); make install

$(DOWNLOADS)/sdl_sound/cmakebuild/Makefile: $(DOWNLOADS)/sdl_sound/CMakeLists.txt
	cd $(DOWNLOADS)/sdl_sound; mkdir -p cmakebuild; cd cmakebuild; \
	$(CMAKE) \
	-DSDLSOUND_BUILD_TEST=false

$(DOWNLOADS)/sdl_sound/CMakeLists.txt:
	$(CLONE) $(GITHUB)/icculus/SDL_sound $(DOWNLOADS)/sdl_sound

# Standard ruby
ruby: init_dirs $(BUILD_PREFIX)/$(RB_PREFIX)-ruby310.dll

$(BUILD_PREFIX)/$(RB_PREFIX)-ruby310.dll: $(DOWNLOADS)/ruby/Makefile
	cd $(DOWNLOADS)/ruby; \
	make -j$(NPROC); make install

$(DOWNLOADS)/ruby/Makefile: $(DOWNLOADS)/ruby/configure
	cd $(DOWNLOADS)/ruby; \
	$(CONFIGURE) $(RUBY_CONFIGURE_ARGS) $(RUBY_FLAGS)

$(DOWNLOADS)/ruby/configure: $(DOWNLOADS)/ruby/*.c
	cd $(DOWNLOADS)/ruby; autoreconf -i

$(DOWNLOADS)/ruby/*.c:
	$(CLONE) $(GITHUB)/ruby/ruby $(DOWNLOADS)/ruby -b ruby_3_1;

libzmq: init_dirs $(LIBDIR)/libzmq.dll

$(LIBDIR)/libzmq.dll: $(DOWNLOADS)/libzmq/Makefile
	cd $(DOWNLOADS)/libzmq; \
	make -j$(NPROC); make install

$(DOWNLOADS)/libzmq/Makefile: $(DOWNLOADS)/libzmq/configure
	cd $(DOWNLOADS)/libzmq; \
	$(CONFIGURE)

$(DOWNLOADS)/libzmq/configure: $(DOWNLOADS)/libzmq/autogen.sh
	cd $(DOWNLOADS)/libzmq; ./autogen.sh

$(DOWNLOADS)/libzmq/autogen.sh:
	$(CLONE) $(GITHUB)/zeromq/libzmq $(DOWNLOADS)/libzmq

zmqpp: init_dirs libzmq $(LIBDIR)/libzmqpp.dll

$(LIBDIR)/libzmqpp.dll: ${DOWNLOADS}/zmqpp/cmakebuild/Makefile
	cd ${DOWNLOADS}/zmqpp/cmakebuild; \
	make -j${NPROC}; make install

$(DOWNLOADS)/zmqpp/cmakebuild/Makefile: $(DOWNLOADS)/zmqpp/CMakeLists.txt
	cd $(DOWNLOADS)/zmqpp; mkdir -p cmakebuild; cd cmakebuild; \
	$(CMAKE)

$(DOWNLOADS)/zmqpp/CMakeLists.txt:
	$(CLONE) $(GITHUB)/somedevfox/zmqpp $(DOWNLOADS)/zmqpp

libnsgif: init_dirs ${LIBDIR}/libnsgif.dll

$(LIBDIR)/libnsgif.dll: $(DOWNLOADS)/libnsgif/Makefile
	cd $(DOWNLOADS)/libnsgif; \
	make -j$(NPROC); make install

$(DOWNLOADS)/libnsgif/Makefile: $(DOWNLOADS)/libnsgif/configure
	cd $(DOWNLOADS)/libnsgif; \
	$(CONFIGURE)

$(DOWNLOADS)/libnsgif/configure: $(DOWNLOADS)/libnsgif/autogen.sh
	cd $(DOWNLOADS)/libnsgif; ./autogen.sh

$(DOWNLOADS)/libnsgif/autogen.sh:
	$(CLONE) $(GITHUB)/jcupitt/libnsgif-autotools $(DOWNLOADS)/libnsgif

# ====
init_dirs:
	@mkdir -p $(LIBDIR) $(INCLUDEDIR)

powerwash: clean-downloads

clean-downloads:
	-rm -rf downloads

deps-core: sdlsound libzmq zmqpp libnsgif
everything: deps-core ruby
